name: CI + Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/llm-chatbot:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/llm-chatbot:latest

      - name: Deploy on Arvan Cloud VM
        uses: appleboy/ssh-action@v1
        with:
          host: 37.32.12.51
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/llm-chatbot:latest
            docker stop llm-chatbot || true
            docker rm llm-chatbot || true
            docker run -d \
              --name llm-chatbot \
              --restart unless-stopped \
              -p 8000:8000 \
              -e GAPGPT_API_KEY=${{ secrets.GAPGPT_API_KEY }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/llm-chatbot:latest
